# Generated by Gemini 😅

#!/usr/bin/env ruby

require 'time'

title = ARGV[0]

if title.nil?
  puts "Error: Please provide a post title."
  exit 1
end

# Get the current time in the system's timezone
current_time = Time.now

# Format the date and time, including timezone offset
date_time_str = current_time.strftime("%Y-%m-%d %H:%M:%S %z")

filename = "./_posts/#{current_time.strftime("%Y-%m-%d")}-#{title.downcase.gsub(' ', '-')}.md"

content = <<~CONTENT
---
title: #{title}
date: #{date_time_str}
---

Write your post content here.
CONTENT

File.open(filename, "w") do |file|
  file.write(content)
end

puts "Created #{filename}"